#!/usr/bin/env bash
#
# claude-alertr installer
# Installs idle-alert hooks into Claude Code's global settings.
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INSTALL_DIR="$HOME/.claude-alertr"
HOOKS_DIR="$INSTALL_DIR/hooks"
CONFIG_FILE="$INSTALL_DIR/config"
CLAUDE_SETTINGS="$HOME/.claude/settings.json"

echo "=== claude-alertr installer ==="
echo ""

# --- Install hooks ---
mkdir -p "$HOOKS_DIR"
cp "$SCRIPT_DIR/hooks/idle-alert.sh" "$HOOKS_DIR/idle-alert.sh"
cp "$SCRIPT_DIR/hooks/dismiss-alert.sh" "$HOOKS_DIR/dismiss-alert.sh"
chmod +x "$HOOKS_DIR/idle-alert.sh" "$HOOKS_DIR/dismiss-alert.sh"
echo "Hooks installed to $HOOKS_DIR"

# --- Create config if it doesn't exist ---
if [ ! -f "$CONFIG_FILE" ]; then
  echo ""
  echo "No config file found. Let's set one up."
  echo ""

  # Worker URL
  read -rp "Enter your claude-alertr Worker URL (e.g. https://claude-alertr.you.workers.dev): " worker_url
  if [ -z "$worker_url" ]; then
    echo "Error: Worker URL is required."
    exit 1
  fi

  # Auth token (optional)
  read -rp "Enter your AUTH_TOKEN (leave blank if none): " auth_token

  # Alert delay
  read -rp "Alert delay in seconds [60]: " delay
  delay="${delay:-60}"

  cat > "$CONFIG_FILE" <<CONF
# claude-alertr configuration
# Generated by install.sh

# URL of your deployed claude-alertr Cloudflare Worker
CLAUDE_ALERTR_URL="$worker_url"

# Auth token (must match AUTH_TOKEN secret on the Worker). Leave empty if not set.
CLAUDE_ALERTR_TOKEN="$auth_token"

# Seconds to wait before sending an alert (default: 60)
CLAUDE_ALERTR_DELAY="$delay"
CONF

  chmod 600 "$CONFIG_FILE"
  echo "Config written to $CONFIG_FILE"
else
  echo "Config already exists at $CONFIG_FILE — skipping."
fi

# --- Update Claude Code global settings ---
echo ""
echo "Configuring Claude Code hooks..."

mkdir -p "$HOME/.claude"

if [ -f "$CLAUDE_SETTINGS" ]; then
  EXISTING=$(cat "$CLAUDE_SETTINGS")
else
  EXISTING="{}"
fi

# Build the hooks configuration using jq
UPDATED=$(echo "$EXISTING" | jq \
  --arg idle_hook "$HOOKS_DIR/idle-alert.sh" \
  --arg dismiss_hook "$HOOKS_DIR/dismiss-alert.sh" \
  '
  .hooks.Notification = [
    {
      "matcher": "",
      "hooks": [
        {
          "type": "command",
          "command": $idle_hook,
          "timeout": 5
        }
      ]
    }
  ]
  |
  .hooks.UserPromptSubmit = [
    {
      "matcher": "",
      "hooks": [
        {
          "type": "command",
          "command": $dismiss_hook,
          "timeout": 5
        }
      ]
    }
  ]
  ')

echo "$UPDATED" | jq '.' > "$CLAUDE_SETTINGS"
echo "Claude Code settings updated at $CLAUDE_SETTINGS"

echo ""
echo "=== Installation complete ==="
echo ""
echo "Next steps:"
echo "  1. Deploy the Worker:  cd $(printf '%q' "$SCRIPT_DIR") && npm run deploy"
echo "  2. Set Worker secrets: wrangler secret put WEBHOOK_URL"
echo "     (and/or RESEND_API_KEY, ALERT_EMAIL_TO for email)"
echo "  3. Test it:            curl -X POST https://your-worker.workers.dev/test"
echo ""
echo "To uninstall, run: $(printf '%q' "$SCRIPT_DIR")/uninstall.sh"
